// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_aSyeVPQSD4o-rJEO7mq9whzOI_1SYeE',
    appId: '1:1047451116542:web:e4c89b9cece9d1e81856af',
    messagingSenderId: '1047451116542',
    projectId: 'learnxchange-781d0',
    authDomain: 'learnxchange-781d0.firebaseapp.com',
    storageBucket: 'learnxchange-781d0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDT_6QWyeR4swmBm_MdkylDEsH6LwAWev8',
    appId: '1:1047451116542:android:23be7aad24fdec291856af',
    messagingSenderId: '1047451116542',
    projectId: 'learnxchange-781d0',
    storageBucket: 'learnxchange-781d0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_V-ZiWlvleYozkbKy06wuNHPw1n_-GLQ',
    appId: '1:1047451116542:ios:09cf8d3ff5a839cf1856af',
    messagingSenderId: '1047451116542',
    projectId: 'learnxchange-781d0',
    storageBucket: 'learnxchange-781d0.firebasestorage.app',
    iosBundleId: 'com.example.learnxchange',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_V-ZiWlvleYozkbKy06wuNHPw1n_-GLQ',
    appId: '1:1047451116542:ios:09cf8d3ff5a839cf1856af',
    messagingSenderId: '1047451116542',
    projectId: 'learnxchange-781d0',
    storageBucket: 'learnxchange-781d0.firebasestorage.app',
    iosBundleId: 'com.example.learnxchange',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_aSyeVPQSD4o-rJEO7mq9whzOI_1SYeE',
    appId: '1:1047451116542:web:bff2a9cd662b39d81856af',
    messagingSenderId: '1047451116542',
    projectId: 'learnxchange-781d0',
    authDomain: 'learnxchange-781d0.firebaseapp.com',
    storageBucket: 'learnxchange-781d0.firebasestorage.app',
  );
}
